swagger: "2.0"
info:
  version: "1.0.0"
  title: "Tessera"

servers:
  - url: http://localhost:3000

basePath: "/api/v1"

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-api-key

security:
  - ApiKeyAuth: []

tags:
  - name: "transactions"
    description: "Describes transactions with pagination"
  - name: "balance"
    description: "Describes balance by address provided"

# In a single file as only 2 endpoints
paths:
  /transactions:
    get:
      tags:
        - transactions
      summary: Get 100 transactions
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: Page number
        - in: query
          name: sort
          type: string
          default: sender
          enum:
            - sender
            - recipient
          description: Sort by sender or recipient
      responses:
        "429":
          description: Too many requests
        200:
          description: A list of transactions
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The unique identifier of the transaction
                        hash:
                          type: string
                          description: The hash of the transaction
                        blockHash:
                          type: string
                          description: The hash of the block containing the transaction
                        blockNumber:
                          type: string
                          description: The number of the block containing the transaction
                        transactionIndex:
                          type: integer
                          description: The index of the transaction in the block
                        sender:
                          type: string
                          description: The address of the sender
                        senderBalance:
                          type: string
                          description: The balance of the sender after the transaction
                        recipient:
                          type: string
                          description: The address of the recipient
                        recipientBalance:
                          type: string
                          description: The balance of the recipient after the transaction
                        gasPrice:
                          type: string
                          description: The gas price of the transaction
                        gasLimit:
                          type: string
                          description: The gas limit of the transaction
                        value:
                          type: string
                          description: The value of the transaction
                        nonce:
                          type: integer
                          description: The nonce of the transaction
                        createdAt:
                          type: string
                          description: The timestamp when the transaction was created
                        updatedAt:
                          type: string
                          description: The timestamp when the transaction was last updated

  /balance/{address}:
    get:
      tags:
        - balance
      summary: Get balance of an address
      parameters:
        - in: path
          name: address
          type: string
          description: address of recipient or sender
      responses:
        "429":
          description: Too many requests
        200:
          description: Balance of an address
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  addressBalance:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The unique identifier of the transaction
                      hash:
                        type: string
                        description: The hash of the transaction
                      blockHash:
                        type: string
                        description: The hash of the block containing the transaction
                      blockNumber:
                        type: string
                        description: The number of the block containing the transaction
                      transactionIndex:
                        type: integer
                        description: The index of the transaction in the block
                      sender:
                        type: string
                        description: The address of the sender
                      senderBalance:
                        type: string
                        description: The balance of the sender after the transaction
                      recipient:
                        type: string
                        description: The address of the recipient
                      recipientBalance:
                        type: string
                        description: The balance of the recipient after the transaction
                      gasPrice:
                        type: string
                        description: The gas price of the transaction
                      gasLimit:
                        type: string
                        description: The gas limit of the transaction
                      value:
                        type: string
                        description: The value of the transaction
                      nonce:
                        type: integer
                        description: The nonce of the transaction
                      createdAt:
                        type: string
                        description: The timestamp when the transaction was created
                      updatedAt:
                        type: string
                        description: The timestamp when the transaction was last updated
