version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 80s  


  node-server:
    build: server
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PG_HOST=host.docker.internal
      - PG_PORT=5432
      - PG_DB=test
      - PG_USER=test
      - PG_PASSWORD=verysecretpassword
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server/:/app
      - /app/node_modules


  node-microservice:
    build: microservice
    restart: always
    environment:
      - PG_HOST=host.docker.internal
      - PG_PORT=5432
      - PG_DB=tessera
      - PG_USER=tessera
      - PG_PASSWORD=verysecretpassword
      - INFURA_API_KEY=02114c24c66d463aa162bdc7fe548d3c
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./microservice/:/app
      - /app/node_modules
